### ISSUE TITLE
#[keep] macro cause error

### ISSUE THREAD

**Issue by xwitch1707** [reply7251/rust-oop#1]
rust edition = "2021"
in your tests folder, i found below class:
<img width="586" alt="image" src="https://github.com/user-attachments/assets/1d985c04-6d4d-490c-9561-a294d85de8bc">
<img width="479" alt="image" src="https://github.com/user-attachments/assets/fb4153d7-dc41-4dbe-93a2-4226bd273c3c">
<img width="537" alt="image" src="https://github.com/user-attachments/assets/841636d1-9269-4afc-944c-f333f1be7b30">

the LandVehicle inherited from Vehicle => OK
the Car inherited from LandVehicle

inside the LandVehicle, i found the method which decorated with #[keep] macro
<img width="422" alt="image" src="https://github.com/user-attachments/assets/4d82d288-8258-4349-82a2-a065ad944e8b">

in original source, no error occurs but when i put one or more parameter to that method, the error occured with the sub class of LandVehicle, the Car class
<img width="525" alt="image" src="https://github.com/user-attachments/assets/49409044-abcb-49ef-a63e-f0736a85b3c2">

error:
<img width="653" alt="image" src="https://github.com/user-attachments/assets/9edc57e1-dbc9-4b81-a836-be704bd7bd48">

below is detail of error when compile:
`% cargo run                   
   Compiling learn-rust v0.1.0 (/Users/xwitch/Documents/NTL/learn-rust)
error[E0415]: identifier `name` is bound more than once in this parameter list
   --> src/oop3.rs:126:1
    |
126 | / class! {
127 | |     extends Dog;
128 | |     pub struct Popi {
129 | |         linh: String
...   |
133 | |     }
134 | | }
    | |_^ used as parameter more than once

warning: unused `#[macro_use]` import
 --> src/main.rs:2:1
  |
2 | #[macro_use] extern crate add_getters_setters;
  | ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0061]: this function takes 5 arguments but 6 arguments were supplied
   --> src/oop3.rs:126:1
    |
126 | / class! {
127 | |     extends Dog;
128 | |     pub struct Popi {
129 | |         linh: String
...   |
133 | |     }
134 | | }
    | | ^
    | | |
    | | unexpected argument of type `String`
    | |_expected `i32`, found `String`
    |   expected `String`, found `i32`
    |
note: associated function defined here
   --> src/oop3.rs:74:1
    |
74  | / class! {
75  | |     extends Animal;
76  | |     pub struct Dog {
77  | |     }
...   |
123 | |     }
124 | | }
    | |_^
    | |_|
    | |_|
    | |_|
    | |_|
    | 
    = note: this error originates in the macro `class` (in Nightly builds, run with -Z macro-backtrace for more info)
help: swap these arguments
    |
134 ~ }(class! {
135 +     extends Dog;
136 +     pub struct Popi {
137 +         linh: String
138 +     }
139 +     impl Popi {
140 +         
141 +     }
142 + }, class! {
143 +     extends Dog;
144 +     pub struct Popi {
145 +         linh: String
146 +     }
147 +     impl Popi {
148 +         
149 +     }
150 + }, class! {
151 +     extends Dog;
152 +     pub struct Popi {
153 +         linh: String
154 +     }
155 +     impl Popi {
156 +         
157 +     }
158 + }, class! {
159 +     extends Dog;
160 +     pub struct Popi {
161 +         linh: String
162 +     }
163 +     impl Popi {
164 +         
165 +     }
166 + }, class! {
167 +     extends Dog;
168 +     pub struct Popi {
169 +         linh: String
170 +     }
171 +     impl Popi {
172 +         
173 +     }
174 + })
    |

warning: unused variable: `name`
  --> src/oop3.rs:84:21
   |
84 |         pub fn with(name: i32) -> Pin<Box<Dog>> where Self: Sized {
   |                     ^^^^ help: if this is intentional, prefix it with an underscore: `_name`
   |
   = note: `#[warn(unused_variables)]` on by default

Some errors have detailed explanations: E0061, E0415.
For more information about an error, try `rustc --explain E0061`.
warning: `learn-rust` (bin "learn-rust") generated 2 warnings
error: could not compile `learn-rust` (bin "learn-rust") due to 2 previous errors; 2 warnings emitted`

1) can you help me to fix this issue?
2) additional, when i try to use the getter setter macro with this lib, i can only generate getter setter for the class with decorated, but the sub class which inherited decorated class cannot use these generated getter setter method? can you create more getter setter macro for that?

**Comment by reply7251** [comment]
fixed in https://github.com/reply7251/rust-oop/commit/d530488932976112c0bbd959f59690722bba4db5

**Comment by xwitch1707** [comment]
can you publish this fix to crates.io with new version?
